In [1]:
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn.neighbors import NearestCentroid
from sklearn.model_selection import train_test_split

In [2]:
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [18]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [3]:
#División del dataset 

X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.30)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (105, 4) (105,)
Test set: (45, 4) (45,)


In [4]:
clasificador = NearestCentroid()
clasificador.fit(X_train,y_train)
y_pred = clasificador.predict(X_test)
clasificador.score(X_test,y_test)

0.9333333333333333

In [5]:
#EVALUACION DEL RENDIMIENTO
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred, normalize=True)

0.9333333333333333

In [10]:
X_test[0]

array([5.5, 2.5, 4. , 1.3])

In [14]:
clasificador.predict([np.array([5.4, 1.5, 2. , 1.3])])

array([0])

In [13]:
y_test[0]

1

In [15]:
y_test

array([1, 2, 2, 2, 2, 1, 1, 1, 0, 2, 2, 0, 2, 1, 1, 1, 1, 0, 0, 0, 2, 2,
       0, 0, 1, 0, 2, 1, 1, 0, 0, 0, 2, 0, 1, 0, 2, 2, 0, 0, 0, 0, 1, 1,
       0])

In [16]:
X_test

array([[5.5, 2.5, 4. , 1.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.1, 3. , 4.9, 1.8],
       [6.6, 2.9, 4.6, 1.3],
       [6.4, 3.2, 4.5, 1.5],
       [6. , 2.7, 5.1, 1.6],
       [5.1, 3.8, 1.6, 0.2],
       [6.5, 3.2, 5.1, 2. ],
       [6.2, 2.8, 4.8, 1.8],
       [5.8, 4. , 1.2, 0.2],
       [6.4, 2.8, 5.6, 2.2],
       [6.1, 2.9, 4.7, 1.4],
       [7. , 3.2, 4.7, 1.4],
       [6.3, 2.5, 4.9, 1.5],
       [5.8, 2.7, 3.9, 1.2],
       [5. , 3.4, 1.6, 0.4],
       [5.1, 3.5, 1.4, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [7.2, 3.6, 6.1, 2.5],
       [6.3, 2.5, 5. , 1.9],
       [5.4, 3.4, 1.7, 0.2],
       [4.6, 3.6, 1. , 0.2],
       [5.9, 3.2, 4.8, 1.8],
       [5.1, 3.4, 1.5, 0.2],
       [7.4, 2.8, 6.1, 1.9],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 2.8, 4.7, 1.2],
       [5. , 3.5, 1.3, 0.3],
       [5. , 3. , 1.6, 0.2],
       [5.1, 3.5, 1.4, 0.3],
       [5.9, 3. , 5.1, 1.8],
       [5.5, 4.2, 1.4, 0.2],
       [6.1, 3