In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn import datasets
import matplotlib.pyplot as plt
from sklearn.neighbors import NearestCentroid

In [2]:
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [5]:
#Definimos la fución de la distancia euclidiana
def dist_euclidiana(a,b):
    dist_eu = np.sqrt(np.sum((a-b)**2))
    return dist_eu

In [9]:
m1 = np.array([2,3,4,5])
patron =np.array([1,1,1,1])
dist_euclidiana(m1,patron)

5.477225575051661

In [34]:
y_train

array([0, 1, 2, 2, 2, 1, 1, 0, 0, 0, 2, 2, 1, 0, 0, 1, 2, 0, 2, 1, 2, 2,
       0, 1, 2, 1, 2, 1, 2, 0, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 2, 0, 0,
       0, 0, 2, 0, 2, 2, 0, 1, 2, 0, 0, 1, 1, 2, 0, 2, 2, 0, 2, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 2, 0, 1, 2, 2, 0, 0, 1, 2, 2, 1, 0, 1, 1, 0,
       0, 1, 2, 0, 1, 0, 0, 2, 0, 1, 0, 2, 1, 0, 1, 0, 2])

In [36]:
# Esto es un contador y hace el mismo trabajo que el enumerate 
k=0
for i in X_train:
    print(k,i)
    k+=1

0 [5.8 4.  1.2 0.2]
1 [6.9 3.1 4.9 1.5]
2 [6.8 3.  5.5 2.1]
3 [7.3 2.9 6.3 1.8]
4 [5.8 2.8 5.1 2.4]
5 [7.  3.2 4.7 1.4]
6 [5.5 2.3 4.  1.3]
7 [5.4 3.4 1.5 0.4]
8 [4.5 2.3 1.3 0.3]
9 [5.2 3.5 1.5 0.2]
10 [6.1 2.6 5.6 1.4]
11 [7.2 3.6 6.1 2.5]
12 [5.6 3.  4.5 1.5]
13 [4.9 3.6 1.4 0.1]
14 [5.1 3.3 1.7 0.5]
15 [6.  2.2 4.  1. ]
16 [5.7 2.5 5.  2. ]
17 [4.8 3.  1.4 0.1]
18 [6.1 3.  4.9 1.8]
19 [6.2 2.2 4.5 1.5]
20 [4.9 2.5 4.5 1.7]
21 [7.1 3.  5.9 2.1]
22 [5.  3.6 1.4 0.2]
23 [5.6 2.5 3.9 1.1]
24 [7.4 2.8 6.1 1.9]
25 [5.5 2.5 4.  1.3]
26 [6.7 3.1 5.6 2.4]
27 [5.7 2.9 4.2 1.3]
28 [6.8 3.2 5.9 2.3]
29 [5.2 4.1 1.5 0.1]
30 [5.1 2.5 3.  1.1]
31 [5.5 2.6 4.4 1.2]
32 [6.3 2.7 4.9 1.8]
33 [5.5 2.4 3.8 1.1]
34 [6.1 2.8 4.7 1.2]
35 [6.  2.9 4.5 1.5]
36 [6.7 3.1 4.7 1.5]
37 [6.6 2.9 4.6 1.3]
38 [5.8 2.7 3.9 1.2]
39 [6.4 3.2 5.3 2.3]
40 [5.9 3.2 4.8 1.8]
41 [6.4 2.8 5.6 2.2]
42 [4.8 3.1 1.6 0.2]
43 [4.9 3.1 1.5 0.2]
44 [4.6 3.1 1.5 0.2]
45 [4.8 3.  1.4 0.3]
46 [6.3 2.5 5.  1.9]
47 [4.7 3.2 1.3 0.2]
48

In [33]:
# Ejemplo del enumerate 
for x,i in enumerate(X_train):
    print(i)
    print(y_train[x])

[5.8 4.  1.2 0.2]
0
[6.9 3.1 4.9 1.5]
1
[6.8 3.  5.5 2.1]
2
[7.3 2.9 6.3 1.8]
2
[5.8 2.8 5.1 2.4]
2
[7.  3.2 4.7 1.4]
1
[5.5 2.3 4.  1.3]
1
[5.4 3.4 1.5 0.4]
0
[4.5 2.3 1.3 0.3]
0
[5.2 3.5 1.5 0.2]
0
[6.1 2.6 5.6 1.4]
2
[7.2 3.6 6.1 2.5]
2
[5.6 3.  4.5 1.5]
1
[4.9 3.6 1.4 0.1]
0
[5.1 3.3 1.7 0.5]
0
[6.  2.2 4.  1. ]
1
[5.7 2.5 5.  2. ]
2
[4.8 3.  1.4 0.1]
0
[6.1 3.  4.9 1.8]
2
[6.2 2.2 4.5 1.5]
1
[4.9 2.5 4.5 1.7]
2
[7.1 3.  5.9 2.1]
2
[5.  3.6 1.4 0.2]
0
[5.6 2.5 3.9 1.1]
1
[7.4 2.8 6.1 1.9]
2
[5.5 2.5 4.  1.3]
1
[6.7 3.1 5.6 2.4]
2
[5.7 2.9 4.2 1.3]
1
[6.8 3.2 5.9 2.3]
2
[5.2 4.1 1.5 0.1]
0
[5.1 2.5 3.  1.1]
1
[5.5 2.6 4.4 1.2]
1
[6.3 2.7 4.9 1.8]
2
[5.5 2.4 3.8 1.1]
1
[6.1 2.8 4.7 1.2]
1
[6.  2.9 4.5 1.5]
1
[6.7 3.1 4.7 1.5]
1
[6.6 2.9 4.6 1.3]
1
[5.8 2.7 3.9 1.2]
1
[6.4 3.2 5.3 2.3]
2
[5.9 3.2 4.8 1.8]
1
[6.4 2.8 5.6 2.2]
2
[4.8 3.1 1.6 0.2]
0
[4.9 3.1 1.5 0.2]
0
[4.6 3.1 1.5 0.2]
0
[4.8 3.  1.4 0.3]
0
[6.3 2.5 5.  1.9]
2
[4.7 3.2 1.3 0.2]
0
[7.7 2.8 6.7 2. ]
2
[6.4 3.1 5.5 1.8]
2


In [14]:
def clasif_euclidiano(X,y,X_test):
    m1=np.zeros(4,)
    m2=np.zeros(4,)
    m3=np.zeros(4,)
    for x,i in enumerate(X):
        if y[x]==0:
            m1 = np.vstack([m1, i])
        elif y[x]==1:
            m2 = np.vstack([m2, i])
        elif y[x]==2:
            m3 = np.vstack([m3, i])
    m1 = m1.mean()
    m2 = m2.mean()
    m3 = m3.mean()
    yhat_=[]
    for patron in X_test:
        yhat_.append(np.argmin([dist_euclidiana(patron,m1),dist_euclidiana(patron,m2),dist_euclidiana(patron,m3)]))
    return yhat_

In [15]:
#División del dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)

In [16]:
y_pred = clasif_euclidiano(X_train,y_train,X_test)

In [22]:
print(y_pred)

[2, 0, 0, 1, 2, 1, 2, 2, 2, 0, 2, 1, 2, 0, 2, 0, 2, 2, 2, 1, 2, 2, 0, 0, 2, 2, 2, 0, 0, 0, 2, 0, 2, 1, 0, 1, 0, 0, 2, 1, 0, 0, 2, 1, 1]


In [23]:
#EVALUACION DEL RENDIMIENTO
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.8888888888888888

In [29]:
clasif_euclidiano(X_train,y_train,np.array([[6.9, 3.2, 5.7, 2.3]]))

[2]

In [28]:
X_test[10]

array([6.9, 3.2, 5.7, 2.3])

In [30]:
y_test[10]

2